import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Box, Button} from '@mui/material'
import Router from "next/router";

export default function Home() {

  const handleGoExam = () => {
    Router.push('/posts')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Chientd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to exam of <a href="https://www.facebook.com/chien.duc.733/">Tạ Đức Chiến</a>
        </h1>
        <Button variant='contained' sx={{marginTop: '50px', padding: '10px 50px'}} onClick={handleGoExam}>Go exam</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Chientd
        </a>
      </footer>
    </div>
  )
}
